### ISSUE TITLE
CMGyroscope and CMDeviceMotion

### ISSUE THREAD

**Issue by DigNeurosurgeon** [shu223/watchOS-2-Sampler#19]
Thanks a lot for this repo. Actually this was for me the best answer that CMDeviceMotion is unavailable on watchOS2 yet **despite** it being mentioned in the official documentation as available. Maybe later on new hardware or a future software upgrade.

Thumbs up!

**Comment by shu223** [comment]
Thanks for your comment. Yes, it is unavailable on current Apple Watch devices, but as an API, it is available and works correctly (returns correctly `false` for `deviceMotionAvailable` because the device doesn't support), so the official documentation is also correct, in my opinion. I hope the future Apple Watch or watchOS support those, too.
